apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  DB_HOST: "aurora-global-tokyo-reader1.c0q1q5z1q5z1.ap-northeast-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "corpportal"
  AWS_REGION: "ap-northeast-1"
  COGNITO_USER_POOL_ID: "ap-northeast-1_lQgwdTN2n"
  COGNITO_CLIENT_ID: "3o5h9d9ovje4o3f2235ahb076c"
