apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  DB_HOST: "aurora-global-seoul-writer.cba24aa6ybd7.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "corpportal"
  DB_USER: "admin"
  COGNITO_REGION: "ap-northeast-2"
  COGNITO_USER_POOL_ID: "ap-northeast-2_aWJI6tXlz"
  COGNITO_CLIENT_ID: "45bms0br1qdsah2iiiqbc2fho7"
  API_PORT: "8080"
