apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: backend-tgb
  namespace: default
  labels:
    app: backend
spec:
  serviceRef:
    name: backend
    port: 8080
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:299145660695:targetgroup/seoul-portal-seoul-tg/f791fe7c0d1c6295
